Repository rago89/DuckDuckGoGroup6, pull requests merged in 2020-10, with the labels that each got.

#5 update of index
  index.html
Labels: enhancement

#6 image folder
  Img/4-alpinist-v2.svg
Labels: documentation

#7 css folder
  css/style.css
Labels: enhancement

#8 Adding images for Dockmain
  Img/DuckDuckGo_logo.png
  Img/arrow.png
  Img/menu.png
  Img/phone-img.png
  Img/search-icon.png
Labels: enhancement

#10 Social media updates
  css/style.css
  index.html
Labels: enhancement

#11 three middle sections added to the respective branch
  Img/arrow-down-scr.png
  Img/arrow.png
  Img/bath.png
  Img/ghost.png
  Img/monster.png
  css/style.css
  index.html
Labels: enhancement, task-1

#12 Duckmain
  index.html
Labels: enhancement

#13 Images for Duckmain
  Img/arrow.svg
  Img/blog.svg
  Img/donations.svg
  Img/mailbox.svg
  Img/newsletter.svg
  Img/privacy-simplified.svg
  Img/privacy-tips.svg
  Img/reddit.svg
  Img/spread.svg
  Img/teaser-2@2x.png
  Img/traffic.svg
  Img/twitter.svg
  Img/woman.svg
Labels: images

#14 Styling for Duckmain
  css/style.css
Labels: enhancement
